apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: supplychain-vaultkubenertes-job
  namespace: supplychain-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: supplychain-vaultkubenertes-job
  chart:
    git: https://github.com/WadeBarnes/bevel.git
    ref: local
    path: platforms/hyperledger-fabric/charts/vault_kubernetes
  values:
    metadata:
      name: supplychain
      component_type: orderer
      namespace: supplychain-net    
      images:
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0

    vault:
      reviewer_service: vault-reviewer
      role: vault-role
      address: http://a7dcfb3cafa6645bebf6768d9f68f70f-1739709432.ca-central-1.elb.amazonaws.com:8200/
      authpath: demo-fabricsupplychain-net-auth
      policy: vault-crypto-orderer-supplychain-net-ro
      secret_path: secretsv2
      serviceaccountname: vault-auth
      imagesecretname: regcred
    
    k8s:
      kubernetes_url: https://0C5A2406F1177773A1F58C7F0A156FCD.yl4.ca-central-1.eks.amazonaws.com
